common:
  gin:
    mode: "debug"

  region:
    region_id: "ap1"

  log:
    filepath: "/var/log"
    level: "debug"
    maxsize: 100
    maxbackups: 7
    maxage: 7

  mysql:
    address: "127.0.0.1:8888"
    dbname: "demo"
    username: "demo"
    password: "12345678"

  api:
    port: "8500"